version: "3.9"

services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    volumes:
      - database-data:/var/lib/postgresql/data
    networks: 
      - default

  backend:
    build: ./django
    command: bash /code/entrypoint.sh
    environment:
      MODE: development
    ports:
      - 8000:8000
    volumes:
      - ./django:/code/
    depends_on: 
      - database
    networks: 
      - default
    
volumes:
  database-data:

networks: 
  default:
    driver: bridge
